baseURL = "https://mdlayher.com/"
languageCode = "en-us"
title = "Matt Layher"
theme = "tale"
pygmentsCodeFences = true
pygmentsStyle = "vs"

[params]
  AuthorName = "Matt Layher"
  Description = "Matt Layher - mdlayher.com"
  Source = "github.com/mdlayher/mdlayher.com"
  css = ["/override.css"]

[markup.goldmark.renderer]
unsafe= true
